import turtle
t = turtle.Turtle()
turtle.title("for crush")
screen = turtle.Screen()
screen.bgcolor("black")
t.color("#E0115F")
t.fillcolor("#E0115F")
t.begin_fill()
t.left(140)
t.forward(180)
t.circle(-90,200)
t.setheading(60)
t.circle(-90,200)
t.forward(100)
t.end_fill()
t.up()
t.setpos(-80,150)
t.down()
t.color("white")
t.write("YASEMİN", False, font = ("Arial", 25, "bold",  ))
t.ht()
turtle.mainloop()